name: Notify on Commit

on:
  push:
    branches:
      - main  

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send Notification
      run: echo "Ada commit baru pada branch main."
